---
- include: install.yml
  when: docker_deployment is not defined
- include: configure.yml
  when: docker_deployment is not defined
- include: supervisord.yml
  when: set_supervisord is defined and docker_deployment is not defined
- include: docker_deploy.yml
  when: docker_deployment is defined
- include: docker_instances.yml
  when: docker_deployment is defined
- include: populate_bouncer_base.yml
  when: docker_deployment is defined and test_helper is not defined
- include: cron.yml
  when: docker_deployment is defined and test_helper is not defined
