---

- name: Deploy slackin containers
  docker_service:
    project_name: slackin
    definition:
      version: '2'
      services:
        https-portal:
          image: steveltn/https-portal:1.0.0
          environment:
            DOMAINS: "{{ slackin_domains }}"
            PRODUCTION: "TRUE"
          ports:
            - "80:80"
            - "443:443"
          links:
            - slackin
        slackin:
          image: chk1/slackin
          ports:
            - "3000:3000"
          environment:
            SLACKIN_VERSION: latest
            SLACK_ORG: "{{ slack_org }}"
            SLACK_TOKEN: "{{ slack_token }}"

- name: Wait for services to start
  pause: minutes=1

- name: Check that Slackin website returns HTTP status 200
  uri:
    url: https://{{ slackin_domains.split(' ')[0] }}
