oonibackend_package: oonibackend

web_connectivity_domain: "{{ letsencrypt_domain_list|selectattr('role', 'equalto', 'web-connectivity')|map(attribute='domain')|list|join(' ') }}"
collector_domain: "{{ letsencrypt_domain_list|selectattr('role', 'equalto', 'collector')|map(attribute='domain')|list|join(' ') }}"
backend_conf_path: "backend-files/{{ ansible_hostname }}_{{ app_env }}"
web_connectivity_hs: "{{lookup('file', '{{ backend_conf_path }}/web_connectivity/hostname')}}"
collector_hs: "{{lookup('file', '{{ backend_conf_path }}/collector/hostname')}}"
bouncer_hs: "{{lookup('file', '{{ backend_conf_path }}/bouncer/hostname')}}"

oonibackend_data_path: /usr/share/ooni/backend
archive_dir: "{{ oonibackend_data_path }}/archive"
tor_datadir: "{{ oonibackend_data_path }}/tor"
bouncer_file: "{{ oonibackend_data_path }}/bouncer.yaml"
policy_file: "{{ oonibackend_data_path }}/policy.yaml"
deck_dir: "{{ oonibackend_data_path }}/decks"
input_dir: "{{ oonibackend_data_path }}/inputs"
report_dir: "{{ oonibackend_data_path }}/raw_reports"
bouncer_hsdir: "{{ tor_datadir }}/bouncer"
collector_hsdir: "{{ tor_datadir }}/collector"
web_connectivity_hsdir: "{{ tor_datadir }}/web_connectivity"
bouncer_update_file: "{{ oonibackend_data_path }}/update-bouncer.py"
oonibackend_tls_dir: "{{ oonibackend_data_path }}/tls"
oonibackend_fullchain: "{{ oonibackend_tls_dir }}/fullchain.pem"
oonibackend_privkey: "{{ oonibackend_tls_dir }}/privkey.pem"
tls_web_connectivity_fullchain: "{{ oonibackend_fullchain }}"
tls_web_connectivity_privkey: "{{ oonibackend_privkey }}"
tls_bouncer_fullchain: "{{ oonibackend_fullchain }}"
tls_bouncer_privkey: "{{ oonibackend_privkey }}"
tls_collector_fullchain: "{{ oonibackend_fullchain }}"
tls_collector_privkey: "{{ oonibackend_privkey }}"
docker_file: "{{ bind_oonibackend_data_path }}/Dockerfile"
bind_archive_dir: "{{ bind_oonibackend_data_path }}/archive"
bind_tor_datadir: "{{ bind_oonibackend_data_path }}/tor"
bind_bouncer_base_file: "{{ bind_oonibackend_data_path }}/bouncer-base.yaml"
bind_policy_file: "{{ bind_oonibackend_data_path }}/policy.yaml"
bind_deck_dir: "{{ bind_oonibackend_data_path }}/decks"
bind_input_dir: "{{ bind_oonibackend_data_path }}/inputs"
bind_report_dir: "{{ bind_oonibackend_data_path }}/raw_reports"
bind_bouncer_hsdir: "{{ bind_tor_datadir }}/bouncer"
bind_collector_hsdir: "{{ bind_tor_datadir }}/collector"
bind_web_connectivity_hsdir: "{{ bind_tor_datadir }}/web_connectivity"
bind_bouncer_file: "{{ bind_oonibackend_data_path }}/bouncer.yaml"
bind_bouncer_update_file: "{{ bind_oonibackend_data_path }}/update-bouncer.py"

oonibackend_install_path: /opt/ooni-backend
oonibackend_log_path: /var/log/ooni
oonibackend_conf_path: /etc/ooni
oonibackend_conf: "{{ oonibackend_conf_path }}/oonibackend.conf"
oonibackend_log_file_name: oonibackend.log
bind_oonibackend_conf_path: "{{ bind_oonibackend_data_path }}/etc/ooni"
bind_oonibackend_log_path: "{{ bind_oonibackend_data_path }}/var/log/ooni"
bind_oonibackend_conf: "{{ bind_oonibackend_conf_path }}/oonibackend.conf"
ooni_sysadmin_repo: "https://github.com/TheTorProject/ooni-sysadmin.git"
ooni_backend_repo: "https://github.com/TheTorProject/ooni-backend.git"
ooni_backend_git_hash: v1.3.3
